<a href="https://colab.research.google.com/github/aditi-tawade-ai/aditi-tawade-ai/blob/main/Notebook/Day19_DS_P2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Data science Operations Part-II**

In [ ]:
path="/content/CO2 Emissions_Canada.csv"

In [ ]:
import pandas as pd
c=pd.read_csv(path)
c.head(1)

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
0,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196

In [ ]:
c[:3]

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
0,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196
1,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221
2,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136

In [ ]:
c.shape

(7385, 12)

In [ ]:
#rename a column/ change column name
#c.rename({old_name:new_name})

c.columns

Index(['Make', 'Model', 'Vehicle Class', 'Engine Size(L)', 'Cylinders',
       'Transmission', 'Fuel Type', 'Fuel Consumption City (L/100 km)',
       'Fuel Consumption Hwy (L/100 km)', 'Fuel Consumption Comb (L/100 km)',
       'Fuel Consumption Comb (mpg)', 'CO2 Emissions(g/km)'],
      dtype='object')

In [ ]:
c.rename(columns={'Fuel Type':'FT'})

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,FT,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
0,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196
1,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221
2,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136
3,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,Z,12.7,9.1,11.1,25,255
4,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244
...,...,...,...,...,...,...,...,...,...,...,...,...
7380,VOLVO,XC40 T5 AWD,SUV - SMALL,2.0,4,AS8,Z,10.7,7.7,9.4,30,219
7381,VOLVO,XC60 T5 AWD,SUV - SMALL,2.0,4,AS8,Z,11.2,8.3,9.9,29,232
7382,VOLVO,XC60 T6 AWD,SUV - SMALL,2.0,4,AS8,Z,11.7,8.6,10.3,27,240
7383,VOLVO,XC90 T5 AWD,SUV - STANDARD,2.0,4,AS8,Z,11.2,8.3,9.9,29,232
7384,VOLVO,XC90 T6 AWD,SUV - STANDARD,2.0,4,AS8,Z,12.2,8.7,10.7,26,248

In [ ]:
c.rename(mapper={'Engine Size(L)': 'ESL'},axis=1)

,Make,Model,Vehicle Class,ESL,Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
0,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196
1,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221
2,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136
3,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,Z,12.7,9.1,11.1,25,255
4,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244
...,...,...,...,...,...,...,...,...,...,...,...,...
7380,VOLVO,XC40 T5 AWD,SUV - SMALL,2.0,4,AS8,Z,10.7,7.7,9.4,30,219
7381,VOLVO,XC60 T5 AWD,SUV - SMALL,2.0,4,AS8,Z,11.2,8.3,9.9,29,232
7382,VOLVO,XC60 T6 AWD,SUV - SMALL,2.0,4,AS8,Z,11.7,8.6,10.3,27,240
7383,VOLVO,XC90 T5 AWD,SUV - STANDARD,2.0,4,AS8,Z,11.2,8.3,9.9,29,232
7384,VOLVO,XC90 T6 AWD,SUV - STANDARD,2.0,4,AS8,Z,12.2,8.7,10.7,26,248

In [ ]:
#access more than one pair
c.rename(mapper={'Engine Size(L)': 'ESL','Model':'MD'},axis=1)

,Make,MD,Vehicle Class,ESL,Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
0,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196
1,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221
2,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136
3,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,Z,12.7,9.1,11.1,25,255
4,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244
...,...,...,...,...,...,...,...,...,...,...,...,...
7380,VOLVO,XC40 T5 AWD,SUV - SMALL,2.0,4,AS8,Z,10.7,7.7,9.4,30,219
7381,VOLVO,XC60 T5 AWD,SUV - SMALL,2.0,4,AS8,Z,11.2,8.3,9.9,29,232
7382,VOLVO,XC60 T6 AWD,SUV - SMALL,2.0,4,AS8,Z,11.7,8.6,10.3,27,240
7383,VOLVO,XC90 T5 AWD,SUV - STANDARD,2.0,4,AS8,Z,11.2,8.3,9.9,29,232
7384,VOLVO,XC90 T6 AWD,SUV - STANDARD,2.0,4,AS8,Z,12.2,8.7,10.7,26,248

In [ ]:
#separate columns with specific data type

c.select_dtypes(include=[float,int])

,Engine Size(L),Cylinders,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
0,2.0,4,9.9,6.7,8.5,33,196
1,2.4,4,11.2,7.7,9.6,29,221
2,1.5,4,6.0,5.8,5.9,48,136
3,3.5,6,12.7,9.1,11.1,25,255
4,3.5,6,12.1,8.7,10.6,27,244
...,...,...,...,...,...,...,...
7380,2.0,4,10.7,7.7,9.4,30,219
7381,2.0,4,11.2,8.3,9.9,29,232
7382,2.0,4,11.7,8.6,10.3,27,240
7383,2.0,4,11.2,8.3,9.9,29,232
7384,2.0,4,12.2,8.7,10.7,26,248

In [ ]:
#number is not built in data type so give quote
c.select_dtypes(include="number")

,Engine Size(L),Cylinders,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
0,2.0,4,9.9,6.7,8.5,33,196
1,2.4,4,11.2,7.7,9.6,29,221
2,1.5,4,6.0,5.8,5.9,48,136
3,3.5,6,12.7,9.1,11.1,25,255
4,3.5,6,12.1,8.7,10.6,27,244
...,...,...,...,...,...,...,...
7380,2.0,4,10.7,7.7,9.4,30,219
7381,2.0,4,11.2,8.3,9.9,29,232
7382,2.0,4,11.7,8.6,10.3,27,240
7383,2.0,4,11.2,8.3,9.9,29,232
7384,2.0,4,12.2,8.7,10.7,26,248

In [ ]:
c.select_dtypes(include='object')

       Make        Model   Vehicle Class Transmission Fuel Type
0     ACURA          ILX         COMPACT          AS5         Z
1     ACURA          ILX         COMPACT           M6         Z
2     ACURA   ILX HYBRID         COMPACT          AV7         Z
3     ACURA      MDX 4WD     SUV - SMALL          AS6         Z
4     ACURA      RDX AWD     SUV - SMALL          AS6         Z
...     ...          ...             ...          ...       ...
7380  VOLVO  XC40 T5 AWD     SUV - SMALL          AS8         Z
7381  VOLVO  XC60 T5 AWD     SUV - SMALL          AS8         Z
7382  VOLVO  XC60 T6 AWD     SUV - SMALL          AS8         Z
7383  VOLVO  XC90 T5 AWD  SUV - STANDARD          AS8         Z
7384  VOLVO  XC90 T6 AWD  SUV - STANDARD          AS8         Z

[7385 rows x 5 columns]

In [ ]:
#in pandas string is not a data type due to hybrid data avaliable
#so here in pds we use object

In [ ]:
c.select_dtypes(include='object').columns

Index(['Make', 'Model', 'Vehicle Class', 'Transmission', 'Fuel Type'], dtype='object')

In [ ]:
#here in nunique we just get no. of unique names available in cat
cat_col=['Make', 'Model', 'Vehicle Class', 'Transmission', 'Fuel Type']

for n in cat_col:
  print(n,':',c[n].nunique())
  print('='*30)

Make : 42
==============================
Model : 2053
==============================
Vehicle Class : 16
==============================
Transmission : 27
==============================
Fuel Type : 5
==============================

In [ ]:
#here it gives names of all unique cat available
cat_col=['Make', 'Model', 'Vehicle Class', 'Transmission', 'Fuel Type']

for n in cat_col:
  print(n,':',c[n].unique())

Make : ['ACURA' 'ALFA ROMEO' 'ASTON MARTIN' 'AUDI' 'BENTLEY' 'BMW' 'BUICK'
 'CADILLAC' 'CHEVROLET' 'CHRYSLER' 'DODGE' 'FIAT' 'FORD' 'GMC' 'HONDA'
 'HYUNDAI' 'INFINITI' 'JAGUAR' 'JEEP' 'KIA' 'LAMBORGHINI' 'LAND ROVER'
 'LEXUS' 'LINCOLN' 'MASERATI' 'MAZDA' 'MERCEDES-BENZ' 'MINI' 'MITSUBISHI'
 'NISSAN' 'PORSCHE' 'RAM' 'ROLLS-ROYCE' 'SCION' 'SMART' 'SRT' 'SUBARU'
 'TOYOTA' 'VOLKSWAGEN' 'VOLVO' 'GENESIS' 'BUGATTI']
Model : ['ILX' 'ILX HYBRID' 'MDX 4WD' ... 'Tacoma 4WD D-Cab TRD Off-Road/Pro'
 'Atlas Cross Sport 4MOTION' 'XC40 T4 AWD']
Vehicle Class : ['COMPACT' 'SUV - SMALL' 'MID-SIZE' 'TWO-SEATER' 'MINICOMPACT'
 'SUBCOMPACT' 'FULL-SIZE' 'STATION WAGON - SMALL' 'SUV - STANDARD'
 'VAN - CARGO' 'VAN - PASSENGER' 'PICKUP TRUCK - STANDARD' 'MINIVAN'
 'SPECIAL PURPOSE VEHICLE' 'STATION WAGON - MID-SIZE'
 'PICKUP TRUCK - SMALL']
Transmission : ['AS5' 'M6' 'AV7' 'AS6' 'AM6' 'A6' 'AM7' 'AV8' 'AS8' 'A7' 'A8' 'M7' 'A4'
 'M5' 'AV' 'A5' 'AS7' 'A9' 'AS9' 'AV6' 'AS4' 'AM5' 'AM8' 'AM9' 'AS10'
 'A10' 'AV10']
Fuel Type : ['Z' 'D' 'X' 'E' 'N']

In [ ]:
#in value_counts we get all vehicle types count separatly in decending order
cat_col=['Make', 'Model', 'Vehicle Class', 'Transmission', 'Fuel Type']

for n in cat_col:
  print(n,':',c[n].value_counts())

Make : Make
FORD             628
CHEVROLET        588
BMW              527
MERCEDES-BENZ    419
PORSCHE          376
TOYOTA           330
GMC              328
AUDI             286
NISSAN           259
JEEP             251
DODGE            246
KIA              231
HONDA            214
HYUNDAI          210
MINI             204
VOLKSWAGEN       197
MAZDA            180
LEXUS            178
JAGUAR           160
CADILLAC         158
SUBARU           140
VOLVO            124
INFINITI         108
BUICK            103
RAM               97
LINCOLN           96
MITSUBISHI        95
CHRYSLER          88
LAND ROVER        85
FIAT              73
ACURA             72
MASERATI          61
ROLLS-ROYCE       50
ASTON MARTIN      47
BENTLEY           46
LAMBORGHINI       41
ALFA ROMEO        30
GENESIS           25
SCION             22
SMART              7
BUGATTI            3
SRT                2
Name: count, dtype: int64
Model : Model
F-150 FFV               32
F-150 FFV 4X4           32
MUSTANG                 27
FOCUS FFV               24
SONIC                   20
                        ..
Camry TRD                1
Cullinan Black Badge     1
1500 4X4 EcoDiesel       1
1500 EcoDiesel           1
Sentra SR                1
Name: count, Length: 2053, dtype: int64
Vehicle Class : Vehicle Class
SUV - SMALL                 1217
MID-SIZE                    1133
COMPACT                     1022
SUV - STANDARD               735
FULL-SIZE                    639
SUBCOMPACT                   606
PICKUP TRUCK - STANDARD      538
TWO-SEATER                   460
MINICOMPACT                  326
STATION WAGON - SMALL        252
PICKUP TRUCK - SMALL         159
MINIVAN                       80
SPECIAL PURPOSE VEHICLE       77
VAN - PASSENGER               66
STATION WAGON - MID-SIZE      53
VAN - CARGO                   22
Name: count, dtype: int64
Transmission : Transmission
AS6     1324
AS8     1211
M6       901
A6       789
A8       490
AM7      445
A9       339
AS7      319
AV       295
M5       193
AS10     168
AM6      132
AV7      118
AV6      113
M7        91
A5        84
AS9       77
A4        65
AM8       62
A7        53
AV8       39
A10       31
AS5       26
AV10      11
AM5        4
AM9        3
AS4        2
Name: count, dtype: int64
Fuel Type : Fuel Type
X    3637
Z    3202
E     370
D     175
N       1
Name: count, dtype: int64

In [ ]:
#if we want just 1st 3 op
cat_col=['Make', 'Model', 'Vehicle Class', 'Transmission', 'Fuel Type']

for n in cat_col:
  print(n,':',c[n].value_counts().head(3))
  print('='*30)

Make : Make
FORD         628
CHEVROLET    588
BMW          527
Name: count, dtype: int64
==============================
Model : Model
F-150 FFV        32
F-150 FFV 4X4    32
MUSTANG          27
Name: count, dtype: int64
==============================
Vehicle Class : Vehicle Class
SUV - SMALL    1217
MID-SIZE       1133
COMPACT        1022
Name: count, dtype: int64
==============================
Transmission : Transmission
AS6    1324
AS8    1211
M6      901
Name: count, dtype: int64
==============================
Fuel Type : Fuel Type
X    3637
Z    3202
E     370
Name: count, dtype: int64
==============================

In [ ]:
c["Make"].value_counts()

Make
FORD             628
CHEVROLET        588
BMW              527
MERCEDES-BENZ    419
PORSCHE          376
TOYOTA           330
GMC              328
AUDI             286
NISSAN           259
JEEP             251
DODGE            246
KIA              231
HONDA            214
HYUNDAI          210
MINI             204
VOLKSWAGEN       197
MAZDA            180
LEXUS            178
JAGUAR           160
CADILLAC         158
SUBARU           140
VOLVO            124
INFINITI         108
BUICK            103
RAM               97
LINCOLN           96
MITSUBISHI        95
CHRYSLER          88
LAND ROVER        85
FIAT              73
ACURA             72
MASERATI          61
ROLLS-ROYCE       50
ASTON MARTIN      47
BENTLEY           46
LAMBORGHINI       41
ALFA ROMEO        30
GENESIS           25
SCION             22
SMART              7
BUGATTI            3
SRT                2
Name: count, dtype: int64

In [ ]:
c.select_dtypes(include='int').columns

Index(['Cylinders', 'Fuel Consumption Comb (mpg)', 'CO2 Emissions(g/km)'], dtype='object')

In [ ]:
it_col=['Cylinders', 'Fuel Consumption Comb (mpg)', 'CO2 Emissions(g/km)']

for i in it_col:
  print(i,':',c[i].nunique())

Cylinders : 8
Fuel Consumption Comb (mpg) : 54
CO2 Emissions(g/km) : 331

In [ ]:
it_col=['Cylinders', 'Fuel Consumption Comb (mpg)', 'CO2 Emissions(g/km)']

for i in it_col:
  print(i,':',c[i].unique())

Cylinders : [ 4  6 12  8 10  3  5 16]
Fuel Consumption Comb (mpg) : [33 29 48 25 27 28 24 31 34 18 19 32 30 26 35 23 21 16 22 20 17 15 42 36
 14 13 40 37 12 11 38 41 39 47 43 51 59 45 46 44 50 60 52 56 54 49 53 55
 63 64 69 66 58 67]
CO2 Emissions(g/km) : [196 221 136 255 244 230 232 267 212 225 239 193 359 338 354 202 214 235
 251 217 262 258 265 224 288 363 242 304 290 336 407 347 409 306 308 293
 285 281 300 292 209 237 314 356 332 380 388 437 200 181 228 213 246 191
 317 260 253 320 370 274 324 278 283 264 250 189 218 207 248 294 382 340
 322 377 271 269 276 179 192 177 163 259 272 366 334 344 362 414 432 411
 419 435 413 229 184 270 299 277 329 173 182 172 159 186 222 301 198 195
 168 331 166 156 138 373 350 396 360 386 368 488 421 216 346 254 402 315
 343 318 175 152 161 205 165 170 162 126 297 110 145 143 345 280 310 223
 147 361 400 342 129 352 194 256 327 398 313 326 358 286 275 393 389 131
 108 384 208 124 180 296 140 379 307 337 238 357 227 416 418 282 226 174
 219 115 120 287 206 412 453 423 133 426 375 273 150 183 178 176 122 185
 249 197 365 390 204 201 211 247 240 257 266 263 408 231 241 210 245 284
 321 215 233 323 199 268 252 289 325 302 261 220 279 335 167 160 190 236
 441 465 298 328 295 188 187 157 312 243 339 353 171 364 203 305 303 309
 341 153 130 234 291 155 169 158 311 420 452 132 139 371 417 476 369 355
 401 348 319 330 403 404 367 134 137 104 111 351 151 450 430 349 438 445
 121 387 333 164 406 114 154 103  96 428 461 372 467 128 141 149 105 135
 378 405 522 118 102 454 464 473 410 397 113 383 381 316 117 487 493 148
 109 392  99 485 395 106 385]

In [ ]:
it_col=['Cylinders', 'Fuel Consumption Comb (mpg)', 'CO2 Emissions(g/km)']

for i in it_col:
  print(i,':',c[i].value_counts())

Cylinders : Cylinders
4     3220
6     2446
8     1402
12     151
3       95
10      42
5       26
16       3
Name: count, dtype: int64
Fuel Consumption Comb (mpg) : Fuel Consumption Comb (mpg)
25    482
29    470
27    461
22    453
26    445
24    399
23    359
31    358
30    333
34    327
20    311
28    310
32    290
21    286
19    265
35    189
33    168
36    163
17    161
18    159
38    147
16    134
37    129
39    101
40     72
15     67
42     45
41     38
43     32
14     30
13     26
50     25
48     16
44     16
47     14
55     12
45     11
60      9
11      8
59      7
49      6
12      6
58      6
46      6
63      5
52      5
56      5
51      4
69      4
53      4
66      2
64      2
54      1
67      1
Name: count, dtype: int64
CO2 Emissions(g/km) : CO2 Emissions(g/km)
242    85
221    82
214    77
230    77
294    76
       ..
148     1
99      1
485     1
395     1
385     1
Name: count, Length: 331, dtype: int64

In [ ]:
#sort data
c.describe()

,Engine Size(L),Cylinders,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
count,7385.000000,7385.000000,7385.000000,7385.000000,7385.000000,7385.000000,7385.000000
mean,3.160068,5.615030,12.556534,9.041706,10.975071,27.481652,250.584699
std,1.354170,1.828307,3.500274,2.224456,2.892506,7.231879,58.512679
min,0.900000,3.000000,4.200000,4.000000,4.100000,11.000000,96.000000
25%,2.000000,4.000000,10.100000,7.500000,8.900000,22.000000,208.000000
50%,3.000000,6.000000,12.100000,8.700000,10.600000,27.000000,246.000000
75%,3.700000,6.000000,14.600000,10.200000,12.600000,32.000000,288.000000
max,8.400000,16.000000,30.600000,20.600000,26.100000,69.000000,522.000000

In [ ]:
#T is transpose operation to convert rows to column and vise versa

In [ ]:
#sort is use to sort data in asending order
#we can sort on the basis of column name and axis
#for column axis=0/index for row axis=1/columns

c.sort_values(by=['CO2 Emissions(g/km)'],axis='index')

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
3824,HYUNDAI,IONIQ BLUE,FULL-SIZE,1.6,4,AM6,X,4.2,4.0,4.1,69,96
6950,HYUNDAI,IONIQ Blue,FULL-SIZE,1.6,4,AM6,X,4.2,4.0,4.1,69,96
4900,HYUNDAI,IONIQ BLUE,FULL-SIZE,1.6,4,AM6,X,4.2,4.0,4.1,69,96
5931,HYUNDAI,IONIQ Blue,FULL-SIZE,1.6,4,AM6,X,4.2,4.0,4.1,69,96
6949,HYUNDAI,IONIQ,FULL-SIZE,1.6,4,AM6,X,4.2,4.2,4.2,67,99
...,...,...,...,...,...,...,...,...,...,...,...,...
7059,LAMBORGHINI,Aventador Roadster,TWO-SEATER,6.5,12,AM7,Z,26.6,15.8,21.7,13,493
6046,LAMBORGHINI,Aventador Roadster,TWO-SEATER,6.5,12,AM7,Z,26.6,15.8,21.7,13,493
5575,BUGATTI,Chiron,TWO-SEATER,8.0,16,AM7,Z,26.8,16.6,22.2,13,522
4509,BUGATTI,CHIRON,TWO-SEATER,8.0,16,AM7,Z,26.8,16.6,22.2,13,522
6640,BUGATTI,Chiron,TWO-SEATER,8.0,16,AM7,Z,26.8,16.6,22.2,13,522