<a href="https://colab.research.google.com/github/aditi-tawade-ai/aditi-tawade-ai/blob/main/Notebook/Day18_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Pandas-Data Analysis**

In [ ]:
# in pandas we have 2 imp. data structures
# 1. series -1D data strut(rows)
# 2. dataframe - 2D data structure (rows)

# Q. whats the difference between series and data frame??
#--> series is for 1D array and dataframe is for 2D array=

In [ ]:
import pandas as pd
data = [120,30,40,55,11]
s=pd.Series(data)
s

0    120
1     30
2     40
3     55
4     11
dtype: int64

In [ ]:
s.ndim

1

In [ ]:
#lets create Data frame
df=pd.DataFrame([[10,20,30],[30,40,50],[100,]])
df

     0     1     2
0   10  20.0  30.0
1   30  40.0  50.0
2  100   NaN   NaN

In [ ]:
df.ndim

2

In [ ]:
#Assignment
#try to create a series and data frame with string,tuple ,list[list],list[tuple],set,dict

In [ ]:
df=pd.DataFrame([['Aditi','Tawade'],['sayee','tawade']])
df

       0       1
0  Aditi  Tawade
1  sayee  tawade

In [ ]:
tp=pd.DataFrame(((10,20,30),(40,50,60)))
tp

    0   1   2
0  10  20  30
1  40  50  60

In [ ]:
lst=pd.DataFrame([[10,[20,30]],[40,50,60]])
lst

    0         1     2
0  10  [20, 30]   NaN
1  40        50  60.0

In [ ]:
lst=pd.DataFrame([[10,(20,30)],[40,50,60]])
lst

    0         1     2
0  10  (20, 30)   NaN
1  40        50  60.0

In [ ]:
st=pd.Series(({10,20,30},{40,50,60}))
st

0    {10, 20, 30}
1    {40, 50, 60}
dtype: object

In [ ]:
st=pd.DataFrame(({10,20,30},{40,50,60}))
st

    0   1   2
0  10  20  30
1  40  50  60

In [ ]:
st.ndim

2

In [ ]:
dt=pd.DataFrame(({'A':1,'B':2},{'C':3,'D':4}))
dt

     A    B    C    D
0  1.0  2.0  NaN  NaN
1  NaN  NaN  3.0  4.0

In [ ]:
dt=pd.Series(({'A':1,'B':2},{'C':3,'D':4}))
dt

0    {'A': 1, 'B': 2}
1    {'C': 3, 'D': 4}
dtype: object

In [ ]:
path = "https://raw.githubusercontent.com/hakimyameen/Datasets/refs/heads/main/fifa_eda.csv"

df = pd.read_csv(path)

df

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
3,193080,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0
4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,238813,J. Lundstram,19,England,47,65,Crewe Alexandra,60.0,1.0,Right,1.0,2.0,CM,2017,2019-01-01,5.750000,134.0,143.0
18203,243165,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,60.0,1.0,Right,1.0,2.0,ST,2018,2020-01-01,6.250000,170.0,113.0
18204,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18205,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
18206,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0

In [ ]:
#display 1st 5 records
#df.head()by default it returns 5 values
df.head(30)

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.000000
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.000000
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.000000
3,193080,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.000000
4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.000000
5,183277,E. Hazard,27,Belgium,91,91,Chelsea,93000.0,340.0,Right,4.0,4.0,LF,2012,2020-01-01,5.666667,163.0,172100.000000
6,177003,L. Modrić,32,Croatia,91,91,Real Madrid,67000.0,420.0,Right,4.0,4.0,RCM,2012,2020-01-01,5.666667,146.0,137400.000000
7,176580,L. Suárez,31,Uruguay,91,91,FC Barcelona,80000.0,455.0,Right,5.0,3.0,RS,2014,2021-01-01,6.000000,190.0,164000.000000
8,155862,Sergio Ramos,32,Spain,91,91,Real Madrid,51000.0,380.0,Right,4.0,3.0,RCB,2005,2020-01-01,6.000000,181.0,104600.000000
9,200389,J. Oblak,25,Slovenia,90,93,Atlético Madrid,68000.0,94.0,Right,3.0,1.0,GK,2014,2021-01-01,6.166667,192.0,144500.000000
10,188545,R. Lewandowski,29,Poland,90,90,FC Bayern München,77000.0,205.0,Right,4.0,4.0,ST,2014,2021-01-01,6.000000,176.0,127100.000000
11,182521,T. Kroos,28,Germany,90,90,Real Madrid,76500.0,355.0,Right,4.0,3.0,LCM,2014,2022-01-01,6.000000,168.0,156800.000000
12,182493,D. Godín,32,Uruguay,90,90,Atlético Madrid,44000.0,125.0,Right,3.0,2.0,CB,2010,2019-01-01,6.166667,172.0,90200.000000
13,168542,David Silva,32,Spain,90,90,Manchester City,60000.0,285.0,Left,4.0,4.0,LCM,2010,2020-01-01,5.666667,148.0,111000.000000
14,215914,N. Kanté,27,France,89,90,Chelsea,63000.0,225.0,Right,3.0,2.0,LDM,2016,2023-01-01,5.500000,159.0,121300.000000
15,211110,P. Dybala,24,Argentina,89,94,Juventus,89000.0,205.0,Left,3.0,4.0,LF,2015,2022-01-01,5.833333,165.0,153500.000000
16,202126,H. Kane,24,England,89,91,Tottenham Hotspur,83500.0,205.0,Right,3.0,3.0,ST,2010,2024-01-01,6.166667,196.0,160700.000000
17,194765,A. Griezmann,27,France,89,90,Atlético Madrid,78000.0,145.0,Left,4.0,4.0,CAM,2014,2023-01-01,5.750000,161.0,165800.000000
18,192448,M. ter Stegen,26,Germany,89,92,FC Barcelona,58000.0,240.0,Right,3.0,1.0,GK,2014,2022-01-01,6.166667,187.0,123300.000000
19,192119,T. Courtois,26,Belgium,89,90,Real Madrid,53500.0,240.0,Left,4.0,1.0,GK,2018,2024-01-01,6.500000,212.0,113700.000000
20,189511,Sergio Busquets,29,Spain,89,89,FC Barcelona,51500.0,315.0,Right,4.0,3.0,CDM,2008,2023-01-01,6.166667,168.0,105600.000000
21,179813,E. Cavani,31,Uruguay,89,89,Paris Saint-Germain,60000.0,200.0,Right,4.0,3.0,LS,2013,2020-01-01,6.083333,170.0,111000.000000
22,167495,M. Neuer,32,Germany,89,89,FC Bayern München,38000.0,130.0,Right,5.0,1.0,GK,2011,2021-01-01,6.333333,203.0,62700.000000
23,153079,S. Agüero,30,Argentina,89,89,Manchester City,64500.0,300.0,Right,4.0,4.0,ST,2011,2021-01-01,5.666667,154.0,119300.000000
24,138956,G. Chiellini,33,Italy,89,89,Juventus,27000.0,215.0,Left,4.0,2.0,LCB,2005,2020-01-01,6.166667,187.0,44600.000000
25,231747,K. Mbappé,19,France,88,95,Paris Saint-Germain,81000.0,100.0,Right,3.0,5.0,RM,2018,2022-01-01,5.833333,161.0,166100.000000
26,209331,M. Salah,26,Egypt,88,89,Liverpool,69500.0,255.0,Left,3.0,4.0,RM,2017,2023-01-01,5.750000,157.0,137300.000000
27,200145,Casemiro,26,Brazil,88,90,Real Madrid,59500.0,285.0,Right,3.0,2.0,CDM,2013,2021-01-01,6.083333,185.0,126400.000000
28,198710,J. Rodríguez,26,Colombia,88,89,FC Bayern München,69500.0,315.0,Left,4.0,4.0,LAM,2016,2019-06-30,5.916667,172.0,4585.060806
29,198219,L. Insigne,27,Italy,88,88,Napoli,62000.0,165.0,Right,3.0,4.0,LW,2010,2022-01-01,5.333333,130.0,105400.000000

In [ ]:
df[:4]  #slicing

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
3,193080,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0

In [ ]:
df[-4:]

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
18203,243165,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,60.0,1.0,Right,1.0,2.0,ST,2018,2020-01-01,6.250000,170.0,113.0
18204,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18205,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
18206,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0

In [ ]:
df.tail(5)

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
18202,238813,J. Lundstram,19,England,47,65,Crewe Alexandra,60.0,1.0,Right,1.0,2.0,CM,2017,2019-01-01,5.750000,134.0,143.0
18203,243165,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,60.0,1.0,Right,1.0,2.0,ST,2018,2020-01-01,6.250000,170.0,113.0
18204,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18205,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
18206,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0

In [ ]:
df[-1:-4:-1]

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
18206,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0
18205,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
18204,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0

In [ ]:
df[-3:]

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
18204,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18205,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
18206,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0

In [ ]:
#summary
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18207 entries, 0 to 18206
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ID                        18207 non-null  int64
 1   Name                      18207 non-null  object
 2   Age                       18207 non-null  int64
 3   Nationality               18207 non-null  object
 4   Overall                   18207 non-null  int64
 5   Potential                 18207 non-null  int64
 6   Club                      17966 non-null  object
 7   Value                     17955 non-null  float64
 8   Wage                      18207 non-null  float64
 9   Preferred Foot            18207 non-null  object
 10  International Reputation  18159 non-null  float64
 11  Skill Moves               18159 non-null  float64
 12  Position                  18207 non-null  object
 13  Joined                    18207 non-null  int64
 14  Contract Valid Until      17918 non-null  object
 15  Height                    18207 non-null  float64
 16  Weight                    18207 non-null  float64
 17  Release Clause            18207 non-null  float64
dtypes: float64(7), int64(5), object(6)
memory usage: 2.5+ MB

In [ ]:
#Q. how to check missing values
df.isna().sum()

ID                            0
Name                          0
Age                           0
Nationality                   0
Overall                       0
Potential                     0
Club                        241
Value                       252
Wage                          0
Preferred Foot                0
International Reputation     48
Skill Moves                  48
Position                      0
Joined                        0
Contract Valid Until        289
Height                        0
Weight                        0
Release Clause                0
dtype: int64

In [ ]:
# total data 1000
#missing data-10/>20----> delete
#if missing data is more 200>400----> handle

In [ ]:
df.isna().sum()/len(df)*100

ID                          0.000000
Name                        0.000000
Age                         0.000000
Nationality                 0.000000
Overall                     0.000000
Potential                   0.000000
Club                        1.323667
Value                       1.384083
Wage                        0.000000
Preferred Foot              0.000000
International Reputation    0.263635
Skill Moves                 0.263635
Position                    0.000000
Joined                      0.000000
Contract Valid Until        1.587302
Height                      0.000000
Weight                      0.000000
Release Clause              0.000000
dtype: float64

In [ ]:
df.dropna()

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
3,193080,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0
4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,238813,J. Lundstram,19,England,47,65,Crewe Alexandra,60.0,1.0,Right,1.0,2.0,CM,2017,2019-01-01,5.750000,134.0,143.0
18203,243165,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,60.0,1.0,Right,1.0,2.0,ST,2018,2020-01-01,6.250000,170.0,113.0
18204,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18205,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
18206,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0

In [ ]:
#lets drop the NaN
#dropna() drops the NaN and gives new temp df and shape gives total
#column n rows after drop
df.dropna().shape

(17907, 18)

In [ ]:
#inplace=true means it modifies the changes permanently to df
df.dropna(inplace=True)

In [ ]:
#check missing values after dropna
df.isna().sum()

ID                          0
Name                        0
Age                         0
Nationality                 0
Overall                     0
Potential                   0
Club                        0
Value                       0
Wage                        0
Preferred Foot              0
International Reputation    0
Skill Moves                 0
Position                    0
Joined                      0
Contract Valid Until        0
Height                      0
Weight                      0
Release Clause              0
dtype: int64

In [ ]:
#Q. drop column
df.columns

Index(['ID', 'Name', 'Age', 'Nationality', 'Overall', 'Potential', 'Club',
       'Value', 'Wage', 'Preferred Foot', 'International Reputation',
       'Skill Moves', 'Position', 'Joined', 'Contract Valid Until', 'Height',
       'Weight', 'Release Clause'],
      dtype='object')

In [ ]:
df.drop(columns=['ID','Nationality','Weight'])

,Name,Age,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Release Clause
0,L. Messi,31,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,226500.0
1,Cristiano Ronaldo,33,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,127100.0
2,Neymar Jr,26,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,228100.0
3,De Gea,27,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,138600.0
4,K. De Bruyne,27,91,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,196400.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,J. Lundstram,19,47,65,Crewe Alexandra,60.0,1.0,Right,1.0,2.0,CM,2017,2019-01-01,5.750000,143.0
18203,N. Christoffersson,19,47,63,Trelleborgs FF,60.0,1.0,Right,1.0,2.0,ST,2018,2020-01-01,6.250000,113.0
18204,B. Worman,16,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,165.0
18205,D. Walker-Rice,17,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,143.0
18206,G. Nugent,16,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,165.0

In [ ]:
df.drop(columns=["ID"],inplace=True)

In [ ]:
df

,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
3,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0
4,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,J. Lundstram,19,England,47,65,Crewe Alexandra,60.0,1.0,Right,1.0,2.0,CM,2017,2019-01-01,5.750000,134.0,143.0
18203,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,60.0,1.0,Right,1.0,2.0,ST,2018,2020-01-01,6.250000,170.0,113.0
18204,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18205,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
18206,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0

In [ ]:
#assignment:convert space to _
#ex. preferred foot-->preferred_foot

In [ ]:
df.columns

Index(['ID', 'Name', 'Age', 'Nationality', 'Overall', 'Potential', 'Club',
       'Value', 'Wage', 'Preferred Foot', 'International Reputation',
       'Skill Moves', 'Position', 'Joined', 'Contract Valid Until', 'Height',
       'Weight', 'Release Clause'],
      dtype='object')

In [ ]:
df.rename(columns={'Preferred Foot':'preferred_foot','Skill Moves':'skill_moves'})

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,preferred_foot,International Reputation,skill_moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
3,193080,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0
4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,238813,J. Lundstram,19,England,47,65,Crewe Alexandra,60.0,1.0,Right,1.0,2.0,CM,2017,2019-01-01,5.750000,134.0,143.0
18203,243165,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,60.0,1.0,Right,1.0,2.0,ST,2018,2020-01-01,6.250000,170.0,113.0
18204,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18205,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
18206,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0

In [ ]:
#try to create a series and data frame with string,tuple ,list[list],list[tuple],set,dict

In [ ]:
# series with string
s=['aditi','tawade','sayee','tawade']
at=pd.Series(s)
at

0     aditi
1    tawade
2     sayee
3    tawade
dtype: object

In [ ]:
# dataframe with string
s=([['aditi','tawade','sayee','tawade']])
at=pd.DataFrame(s)
at

       0       1      2       3
0  aditi  tawade  sayee  tawade

In [ ]:
#series with tuple
s=(10,20,30,40,50)
at=pd.Series(s)
at

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [ ]:
#dataframe with tuple
s=([[10,20,30,40,50]])
at=pd.DataFrame(s)
at

    0   1   2   3   4
0  10  20  30  40  50

In [ ]:
#series with list in list
s=[10,20,[30,40],50]
b=pd.Series(s)
b

0          10
1          20
2    [30, 40]
3          50
dtype: object

In [ ]:
b.ndim

1

In [ ]:
#series with list in list
s=[[10,20,[30,40],50]]
c=pd.DataFrame(s)
c

    0   1         2   3
0  10  20  [30, 40]  50

In [ ]:
a=([10,20,30],[40,50,60])
d=pd.DataFrame(a)
d

    0   1   2
0  10  20  30
1  40  50  60

In [ ]:
d.ndim

2

In [ ]:
c.ndim

2

In [ ]:
#list in tuple series
s=[(10,(20,30)),(40,50,60)]
b=pd.Series(s)
b

0    (10, (20, 30))
1      (40, 50, 60)
dtype: object

In [ ]:
#tuple list data frame
s=[(10,(20,30)),(40,50,60)]
c=pd.DataFrame(s)
c

    0         1     2
0  10  (20, 30)   NaN
1  40        50  60.0

In [ ]:
#set
s=([{10,20,30,40,50}])
b=pd.Series(s)
b

0    {50, 20, 40, 10, 30}
dtype: object

In [ ]:
s=([{10,20,30,40,50},{60,70,}])
c=pd.DataFrame(s)
c

    0   1     2     3     4
0  50  20  40.0  10.0  30.0
1  60  70   NaN   NaN   NaN

In [ ]:
c.isna().sum()

0    0
1    0
2    1
3    1
4    1
dtype: int64

In [ ]:
c.dropna(inplace=True)
c

    0   1     2     3     4
0  50  20  40.0  10.0  30.0

In [ ]:
s=({'A':1,'B':2,'C':3,'D':4})
b=pd.Series(s)
b

A    1
B    2
C    3
D    4
dtype: int64

In [ ]:
#dict series
s=([{'A':1,'B':2,'C':3,'D':4},
   {'A':5,'B':6,'C':7,'D':8}])
b=pd.DataFrame(s)
b

   A  B  C  D
0  1  2  3  4
1  5  6  7  8

In [ ]:
b.ndim

1

In [ ]:
#dict with dataf
s=({'A':1,'B':2},{'C':3,'D':4})
b=pd.DataFrame(s)
b

     A    B    C    D
0  1.0  2.0  NaN  NaN
1  NaN  NaN  3.0  4.0

In [ ]:
b.ndim

2

# **Part -II pandas**

In [ ]:
set_Data = {1,2,3,4,5,6,7,8,9,10}
pd.Series(list(set_Data))

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [ ]:
path = "https://raw.githubusercontent.com/hakimyameen/Datasets/refs/heads/main/fifa_eda.csv"

df = pd.read_csv(path)

df

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
3,193080,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0
4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,238813,J. Lundstram,19,England,47,65,Crewe Alexandra,60.0,1.0,Right,1.0,2.0,CM,2017,2019-01-01,5.750000,134.0,143.0
18203,243165,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,60.0,1.0,Right,1.0,2.0,ST,2018,2020-01-01,6.250000,170.0,113.0
18204,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18205,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
18206,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0

**Row and column operations**

In [ ]:
df[:1]

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0

In [ ]:
df[-1:]

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
18206,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0

In [ ]:
df[:3,'Club']   #we cannot access both rows and columns with slicing

InvalidIndexError: (slice(None, 3, None), 'Club')

In [ ]:
df.loc[:3,'Name':'Club']

                Name  Age Nationality  Overall  Potential                 Club
0           L. Messi   31   Argentina       94         94         FC Barcelona
1  Cristiano Ronaldo   33    Portugal       94         94             Juventus
2          Neymar Jr   26      Brazil       92         93  Paris Saint-Germain
3             De Gea   27       Spain       91         93    Manchester United

In [ ]:
#access single column
df['Nationality']

0        Argentina
1         Portugal
2           Brazil
3            Spain
4          Belgium
           ...
18202      England
18203       Sweden
18204      England
18205      England
18206      England
Name: Nationality, Length: 18207, dtype: object

In [ ]:
#approach 2 using dot. operator
#we can access only single word column by dot
df.Age

0        31
1        33
2        26
3        27
4        27
         ..
18202    19
18203    19
18204    16
18205    17
18206    16
Name: Age, Length: 18207, dtype: int64

In [ ]:
df.Skill Moves

SyntaxError: invalid syntax (2407076848.py, line 1)

In [ ]:
df.columns

Index(['ID', 'Name', 'Age', 'Nationality', 'Overall', 'Potential', 'Club',
       'Value', 'Wage', 'Preferred Foot', 'International Reputation',
       'Skill Moves', 'Position', 'Joined', 'Contract Valid Until', 'Height',
       'Weight', 'Release Clause'],
      dtype='object')

In [ ]:
df['Skill Moves']

0        4.0
1        5.0
2        5.0
3        1.0
4        4.0
        ...
18202    2.0
18203    2.0
18204    2.0
18205    2.0
18206    2.0
Name: Skill Moves, Length: 18207, dtype: float64

In [ ]:
#access more than one columns use--->  [[]]

df[['Value','Wage','Weight','Skill Moves']]

          Value   Wage  Weight  Skill Moves
0      110500.0  565.0   159.0          4.0
1       77000.0  405.0   183.0          5.0
2      118500.0  290.0   150.0          5.0
3       72000.0  260.0   168.0          1.0
4      102000.0  355.0   154.0          4.0
...         ...    ...     ...          ...
18202      60.0    1.0   134.0          2.0
18203      60.0    1.0   170.0          2.0
18204      60.0    1.0   148.0          2.0
18205      60.0    1.0   154.0          2.0
18206      60.0    1.0   176.0          2.0

[18207 rows x 4 columns]

In [ ]:
df[['Value','Wage','Weight','Skill Moves','Club']].head(4)

      Value   Wage  Weight  Skill Moves                 Club
0  110500.0  565.0   159.0          4.0         FC Barcelona
1   77000.0  405.0   183.0          5.0             Juventus
2  118500.0  290.0   150.0          5.0  Paris Saint-Germain
3   72000.0  260.0   168.0          1.0    Manchester United

In [ ]:
#Access rows and column we have 2 more options present in pandas
#loc-- lable based selection
#stop is inclusive not exclusive
df.loc[:3,'Name':'Overall']   #[row,column]

                Name  Age Nationality  Overall
0           L. Messi   31   Argentina       94
1  Cristiano Ronaldo   33    Portugal       94
2          Neymar Jr   26      Brazil       92
3             De Gea   27       Spain       91

In [ ]:
df.loc[:5,:]

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
3,193080,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0
4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0
5,183277,E. Hazard,27,Belgium,91,91,Chelsea,93000.0,340.0,Right,4.0,4.0,LF,2012,2020-01-01,5.666667,163.0,172100.0

In [ ]:
df.loc[:3,'Name':'Club']

                Name  Age Nationality  Overall  Potential                 Club
0           L. Messi   31   Argentina       94         94         FC Barcelona
1  Cristiano Ronaldo   33    Portugal       94         94             Juventus
2          Neymar Jr   26      Brazil       92         93  Paris Saint-Germain
3             De Gea   27       Spain       91         93    Manchester United

In [ ]:
df.loc[:3,'Nationality':'Club']

  Nationality  Overall  Potential                 Club
0   Argentina       94         94         FC Barcelona
1    Portugal       94         94             Juventus
2      Brazil       92         93  Paris Saint-Germain
3       Spain       91         93    Manchester United

In [ ]:
df.loc[:-5:-2,:]

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
18206,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0
18204,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18202,238813,J. Lundstram,19,England,47,65,Crewe Alexandra,60.0,1.0,Right,1.0,2.0,CM,2017,2019-01-01,5.750000,134.0,143.0
18200,231381,J. Young,18,Scotland,47,62,Swindon Town,60.0,1.0,Left,1.0,2.0,ST,2015,2019-01-01,5.750000,157.0,143.0
18198,242844,J. Livesey,18,England,47,70,Burton Albion,60.0,1.0,Right,1.0,1.0,GK,2018,2021-01-01,5.916667,154.0,165.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8,155862,Sergio Ramos,32,Spain,91,91,Real Madrid,51000.0,380.0,Right,4.0,3.0,RCB,2005,2020-01-01,6.000000,181.0,104600.0
6,177003,L. Modrić,32,Croatia,91,91,Real Madrid,67000.0,420.0,Right,4.0,4.0,RCM,2012,2020-01-01,5.666667,146.0,137400.0
4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0

In [ ]:
df.loc[:2,:]

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0

In [ ]:
df.loc[:3,['Name','Club','Nationality','Age']]

                Name                 Club Nationality  Age
0           L. Messi         FC Barcelona   Argentina   31
1  Cristiano Ronaldo             Juventus    Portugal   33
2          Neymar Jr  Paris Saint-Germain      Brazil   26
3             De Gea    Manchester United       Spain   27

In [ ]:
#iloc --> index based selection
#stop is exclusive
df.iloc[:2,:3]

       ID               Name  Age
0  158023           L. Messi   31
1   20801  Cristiano Ronaldo   33

In [ ]:
#Q. difference between loc and iloc

In [ ]:
df.iloc[:5,:3]

       ID               Name  Age
0  158023           L. Messi   31
1   20801  Cristiano Ronaldo   33
2  190871          Neymar Jr   26
3  193080             De Gea   27
4  192985       K. De Bruyne   27

In [ ]:
df.iloc[:9,[10,3,5,4]]

   International Reputation Nationality  Potential  Overall
0                       5.0   Argentina         94       94
1                       5.0    Portugal         94       94
2                       5.0      Brazil         93       92
3                       4.0       Spain         93       91
4                       4.0     Belgium         92       91
5                       4.0     Belgium         91       91
6                       4.0     Croatia         91       91
7                       5.0     Uruguay         91       91
8                       4.0       Spain         91       91

In [ ]:
#use random index
df.iloc[:2,[10,3,5,1]]

   International Reputation Nationality  Potential               Name
0                       5.0   Argentina         94           L. Messi
1                       5.0    Portugal         94  Cristiano Ronaldo

In [ ]:
#keep the copy of original before making changes
new_df=df.copy()

In [ ]:
df.drop(columns=['Club','ID','Name'])

,Age,Nationality,Overall,Potential,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,31,Argentina,94,94,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,33,Portugal,94,94,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,26,Brazil,92,93,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
3,27,Spain,91,93,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0
4,27,Belgium,91,92,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,19,England,47,65,60.0,1.0,Right,1.0,2.0,CM,2017,2019-01-01,5.750000,134.0,143.0
18203,19,Sweden,47,63,60.0,1.0,Right,1.0,2.0,ST,2018,2020-01-01,6.250000,170.0,113.0
18204,16,England,47,67,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18205,17,England,47,66,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
18206,16,England,46,66,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0

In [ ]:
# check duplicate records count
df.duplicated().sum()

np.int64(0)

In [ ]:
#here we have no duplicates
#but if any then we can remove them using drop_duplicates()

df.drop_duplicates()

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
3,193080,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0
4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,238813,J. Lundstram,19,England,47,65,Crewe Alexandra,60.0,1.0,Right,1.0,2.0,CM,2017,2019-01-01,5.750000,134.0,143.0
18203,243165,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,60.0,1.0,Right,1.0,2.0,ST,2018,2020-01-01,6.250000,170.0,113.0
18204,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18205,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
18206,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0

In [ ]:
#add a new column in existing dataframe

df['New_name']='Aditi'
df

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause,New_name
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0,Aditi
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0,Aditi
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0,Aditi
3,193080,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0,Aditi
4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0,Aditi
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,238813,J. Lundstram,19,England,47,65,Crewe Alexandra,60.0,1.0,Right,1.0,2.0,CM,2017,2019-01-01,5.750000,134.0,143.0,Aditi
18203,243165,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,60.0,1.0,Right,1.0,2.0,ST,2018,2020-01-01,6.250000,170.0,113.0,Aditi
18204,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0,Aditi
18205,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0,Aditi
18206,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0,Aditi

In [ ]:
#assignment:
#how to add a row in df
#how to append two dataframe
#how to concatanate two or more dataframe
#how to perform merge operations
#how to perform join operations

In [ ]:
#githun --- pandas exercises
#kaggle

# **Assignment**

In [ ]:
import pandas as pd

In [ ]:
a=pd.DataFrame([{'Name':'Aditi','Age':22,'Gender':'female'},
                {'Name':'Avanish','Age':15,'Gender':'Male'}])
a

      Name  Age  Gender
0    Aditi   22  female
1  Avanish   15    Male

In [ ]:
a.loc[len(a)]=['sayee',16,'female']
a

      Name  Age  Gender
0    Aditi   22  female
1  Avanish   15    Male
2    sayee   16  female
3    sayee   16  female
4    sayee   16  female
5    sayee   16  female

In [ ]:
a

      Name  Age Gender
1  Avanish   15   Male

In [ ]:
a=pd.DataFrame([{'Name':'Aditi','Age':22,'Gender':'female'},
                {'Name':'Avanish','Age':15,'Gender':'Male'}])
a

      Name  Age  Gender
0    Aditi   22  female
1  Avanish   15    Male

In [ ]:
a.loc[len(a)]=['sayee',16,'female']
a

      Name  Age  Gender
0    Aditi   22  female
1  Avanish   15    Male
2    sayee   16  female
3    sayee   16  female

In [ ]:
a=a.drop(3)
a

      Name  Age  Gender
0    Aditi   22  female
1  Avanish   15    Male
2    sayee   16  female

In [ ]:
b=pd.DataFrame([{'School':'Shantiniketan'},
 {'School':'Shantiniketan'},{'School':'Vimla Goenka'}])
b

          School
0  Shantiniketan
1  Shantiniketan
2   Vimla Goenka

In [ ]:
#append 2 dataframes
c=pd.concat([a,b])   #this adds rows
c

      Name   Age  Gender         School
0    Aditi  22.0  female            NaN
1  Avanish  15.0    Male            NaN
2    sayee  16.0  female            NaN
0      NaN   NaN     NaN  Shantiniketan
1      NaN   NaN     NaN  Shantiniketan
2      NaN   NaN     NaN   Vimla Goenka

In [ ]:
#adds rows
c=pd.concat([a,b],axis=1)
c

      Name  Age  Gender         School
0    Aditi   22  female  Shantiniketan
1  Avanish   15    Male  Shantiniketan
2    sayee   16  female   Vimla Goenka

In [ ]:
#how to concatanate 2 or more dataframes
a=pd.DataFrame([{'Name':'Aditi','Age':22,'Gender':'female'},
                {'Name':'Avanish','Age':15,'Gender':'Male'},
                {'Name':'Sayee','Age':16,'Gender':'Female'}])
b=pd.DataFrame([{'School':'Shantiniketan'},
 {'School':'Shantiniketan'},{'School':'Vimla Goenka'}])
c=pd.DataFrame([{'Roll no':201},{'Roll no':202},{'Roll no':203}])
d=pd.concat([a,b,c],axis=1)
d

      Name  Age  Gender         School  Roll no
0    Aditi   22  female  Shantiniketan      201
1  Avanish   15    Male  Shantiniketan      202
2    Sayee   16  Female   Vimla Goenka      203

In [ ]:
#how to perform merge operations
data=pd.DataFrame({'Names':['Aditi','Avanish','Sayee'],
                    'Roll no':[201,202,203]})
data2=pd.DataFrame({'Roll no':[201,202,203],
                     'School':['Shantiniketan','Shantiniketan','Vimla Goenka']})
final=pd.merge(data,data2,on='Roll no')
final

     Names  Roll no         School
0    Aditi      201  Shantiniketan
1  Avanish      202  Shantiniketan
2    Sayee      203   Vimla Goenka

In [ ]:
#how to perform join operation